name: glukofit
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  appwrite: 12.0.3
  cached_network_image: ^3.4.0
  camera: ^0.11.0+1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dash_chat_2: ^0.0.21
  dio: ^5.6.0
  easy_date_timeline: ^1.1.3
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_tflite: ^1.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  image_picker: ^0.8.9
  horizontal_picker: ^1.2.0
  intl: ^0.19.0
  logger: ^2.4.0
  numberpicker: ^2.1.2
  permission_handler: ^11.3.1
  flutter_staggered_grid_view: ^0.7.0
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_gauges: ^26.2.8
  timeline_tile: ^2.0.0
  flutter_quill: ^10.5.14
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/tensorflow/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
