name: glukofit
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  appwrite: 12.0.3
  cached_network_image: ^3.4.0
  camera: ^0.11.0+1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_tflite: ^1.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  logger: ^2.4.0
  permission_handler: ^11.3.1
  step_progress_indicator: ^1.0.2
  syncfusion_flutter_gauges: ^26.2.8

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/tensorflow/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
